name: Sync Labels

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"

permissions:
  contents: read
  issues: write

jobs:
  sync:
    name: Sync Repository Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Sync labels
        uses: endbug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: false
